<div style="float: right" markdown="1">
    <img src="http://www.numpy.org/_static/numpy_logo.png">
</div>
# NumPy

En este notebook encontrarán algunos ejemplos basicos sobre el uso de la libreria NumPy de python.

Para crear arrays en NumPy hay tres formas de hacerlo:

   1. A partir de secuencias (Listas o tuplas) de python
   2. Usando funciones de NumPy
   3. Lectura de datos desde ficheros
   4. Copiando desde otro array
    
### Manejo o manipulación basica de arrays

Los arrays tiene un manejo de sus elementos muy similares a las listas o tuplas,puesto que su contenido también está indexado.
Para acceder a un elemento de array, se hace de la misma forma que en una lista: *se indica la posición del elemento mediante un indice entero entre corchetes **[ ]** *

Las formas básicas de selección de los elementos de un array de numpy son:

|       Tipo de selección      |  Sintaxis |
|:----------------------------:|:---------:|
| Un solo elemento             |  $x[i]$   |
| Varios elementos             |  $x[i:j]$ |
| Una rebanada de elementos    |  $x[start:end:step]$ |
| Elementos en cualquier orden |  $x[[p_1,p_2,...,p_k]]$   |
                     

In [31]:
# Se importa la libreria NumPy con el alias np
import numpy as np

# Se crea un array utilizando funciones de NumPy
a = np.arange(1,21)
#Se muestra todo el arreglo
print a
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
z = np.arange(1,21,0.1) #Notación de intervalos: [start, stop)
print ("tamaño:", z.size) # El tamaño está dado por (stop-start)/step
print (z)

tamaño: 200
[  1.    1.1   1.2   1.3   1.4   1.5   1.6   1.7   1.8   1.9   2.    2.1
   2.2   2.3   2.4   2.5   2.6   2.7   2.8   2.9   3.    3.1   3.2   3.3
   3.4   3.5   3.6   3.7   3.8   3.9   4.    4.1   4.2   4.3   4.4   4.5
   4.6   4.7   4.8   4.9   5.    5.1   5.2   5.3   5.4   5.5   5.6   5.7
   5.8   5.9   6.    6.1   6.2   6.3   6.4   6.5   6.6   6.7   6.8   6.9
   7.    7.1   7.2   7.3   7.4   7.5   7.6   7.7   7.8   7.9   8.    8.1
   8.2   8.3   8.4   8.5   8.6   8.7   8.8   8.9   9.    9.1   9.2   9.3
   9.4   9.5   9.6   9.7   9.8   9.9  10.   10.1  10.2  10.3  10.4  10.5
  10.6  10.7  10.8  10.9  11.   11.1  11.2  11.3  11.4  11.5  11.6  11.7
  11.8  11.9  12.   12.1  12.2  12.3  12.4  12.5  12.6  12.7  12.8  12.9
  13.   13.1  13.2  13.3  13.4  13.5  13.6  13.7  13.8  13.9  14.   14.1
  14.2  14.3  14.4  14.5  14.6  14.7  14.8  14.9  15.   15.1  15.2  15.3
  15.4  15.5  15.6  15.7  15.8  15.9  16.   16.1  16.2  16.3  16.4  16.5
  16.6  16.7  16.8  16.9  17.   17.1  1

In [3]:
#Se muestra el elemento con indice i:3
a[3]

4

In [10]:
#Se muestran los elementos desde el indice i=2 hasta el indice i=6
a[2:7]

array([3, 4, 5, 6, 7])

In [37]:
# Se le pasa una lista con las posiciones deseadas (no necesariamente consecutivas).
# Esto es algo nuevo, en comparación con las listas o tuplas en python
a[[2,5,7,10,15,19]]

array([ 3,  6,  8, 11, 16, 20])

Notese que el extraer varios elementos de un array, genera otro array.  
Los indices del array tambien pueden tomar valores negativos.

In [12]:
# Muestra el elemento i:1 y el ultimo elemento
a[1],a[-1]

(2, 20)

In [13]:
# muestra el elemento i:3, el elemento i:16 y una array con i desde 3 hasta 16
a[3],a[-4],a[3:-4]

(4, 17, array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]))

In [14]:
#Muestra los tres ultimos elementos
a[-3:]

array([18, 19, 20])

In [15]:
# Muestra los elementos del array de 2 en 2
a[0:11:2]

array([ 1,  3,  5,  7,  9, 11])

In [15]:
#Utilizando la función linspace de NumPy
b = np.linspace(1,21,20)
print (b)
print (b.size)

c = np.linspace(0,21,20, endpoint=True)
print ("c=", c)

d = np.linspace(0,21,20, endpoint=False)
print ("d=", d)

[  1.           2.05263158   3.10526316   4.15789474   5.21052632
   6.26315789   7.31578947   8.36842105   9.42105263  10.47368421
  11.52631579  12.57894737  13.63157895  14.68421053  15.73684211
  16.78947368  17.84210526  18.89473684  19.94736842  21.        ]
20
c= [  0.           1.10526316   2.21052632   3.31578947   4.42105263
   5.52631579   6.63157895   7.73684211   8.84210526   9.94736842
  11.05263158  12.15789474  13.26315789  14.36842105  15.47368421
  16.57894737  17.68421053  18.78947368  19.89473684  21.        ]
d= [  0.     1.05   2.1    3.15   4.2    5.25   6.3    7.35   8.4    9.45
  10.5   11.55  12.6   13.65  14.7   15.75  16.8   17.85  18.9   19.95]


In [26]:
#Ejecutando algunas funciones matemáticas de NumPy
angulos = np.array([45,90,180,225,315])
ang_rad = np.radians(angulos)

print ("angulos = ", angulos)
print ("en radianes = ", ang_rad)

sen_ang = np.sin(ang_rad)
print ("Funcion seno de cada ángulo:", sen_ang)

angulos =  [ 45  90 180 225 315]
en radianes =  [ 0.78539816  1.57079633  3.14159265  3.92699082  5.49778714]
Funcion seno de cada ángulo: [  7.07106781e-01   1.00000000e+00   1.22464680e-16  -7.07106781e-01
  -7.07106781e-01]


In [29]:
#Abrebocas a la graficación
ang_rad = np.linspace(0.0,6.2,50)
sen_ang = np.sin(ang_rad)

print (ang_rad)
print (sen_ang)

from matplotlib import pyplot
pyplot.plot(ang_rad, sen_ang, 'ro')
pyplot.show()

[ 0.          0.12653061  0.25306122  0.37959184  0.50612245  0.63265306
  0.75918367  0.88571429  1.0122449   1.13877551  1.26530612  1.39183673
  1.51836735  1.64489796  1.77142857  1.89795918  2.0244898   2.15102041
  2.27755102  2.40408163  2.53061224  2.65714286  2.78367347  2.91020408
  3.03673469  3.16326531  3.28979592  3.41632653  3.54285714  3.66938776
  3.79591837  3.92244898  4.04897959  4.1755102   4.30204082  4.42857143
  4.55510204  4.68163265  4.80816327  4.93469388  5.06122449  5.1877551
  5.31428571  5.44081633  5.56734694  5.69387755  5.82040816  5.94693878
  6.07346939  6.2       ]
[ 0.          0.12619326  0.25036885  0.37054139  0.48478947  0.59128643
  0.68832951  0.77436714  0.84802368  0.90812147  0.95369963  0.98402942
  0.99862592  0.99725573  0.97994077  0.94695789  0.89883443  0.83633983
  0.76047328  0.67244779  0.57367077  0.46572154  0.35032604  0.22932931
  0.10466591 -0.02167096 -0.14766133 -0.2712908  -0.3905827  -0.50362971
 -0.60862436 -0.70388794 -

### Arrays N-Dimensionales

Se pueden crear de la misma forma que un array simple:

   1.  Haciendo uso de listas de listas o tuplas de tuplas  
   2.  Usando funciones de NumPy  
   3.  Leyendo desde ficheros  
   4.  Copiando o extrayendo de otro array  
   5.  Haciendo uso de la propiedad shape o del metodo reshape

In [16]:
# Usando la forma 1:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print (a)
print ("SHAPE: ", a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
SHAPE:  (3, 4)


In [17]:
#Usando la forma 2:
a1 = np.ones((2,3))
a0 = np.zeros((2,3))
print (a0)
print (a1)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [18]:
# Usando shape:
a = np.arange(10)
print (" a: ",a)
a.shape = [2,5]
a

 a:  [0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
# Usando reshape
a = np.arange(10)
print ("a: ", a,"\n")
b = a.reshape((2,5))
print ("b: ",b)

a:  [0 1 2 3 4 5 6 7 8 9] 

b:  [[0 1 2 3 4]
 [5 6 7 8 9]]


La sintaxis para obtener un elemento de la matriz con arrays, difiere de la forma en que se obtiene para una lista:  

In [20]:
# Obteniendo el elemento en la fila 1 y columna 2
b[1,2]

7

In [38]:
#Se crea un array de 5x5
A = np.arange(25)
A.shape = (5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Tambien se puede rebanar de forma indexada una matriz

In [5]:
A[1:3,2:4]

array([[ 7,  8],
       [12, 13]])

In [9]:
#Obteniendo elementos de dos en dos
B = A[::2,::2]
B

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

Se pueden utilizar etiquetas para los indices del array. Esta es una forma elegante y util en algunos casos.

In [10]:
i,j=0,2
A[i,j]

2

Se pueden utilizar listas como indices de la misma forma:

In [11]:
filas = [0,2,4]
columnas = [1,2,3]
A[filas]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [12]:
A[filas,columnas]

array([ 1, 12, 23])

Los indices pueden ser datos booleanos, es decir _TRUE_ o _FALSE_

In [39]:
mask_1 = np.array([True,True,True,True,True])
mask_2 = np.array([True,False,True,False,True])

In [40]:
A[mask_1]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
A[mask_2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [44]:
x = np.arange(5)
print (x)
mask=np.array([True,True,False,True,False],dtype=bool)
x[mask]

[0 1 2 3 4]


array([0, 1, 3])

Esto es util cuando se quieren evaluar condiciones en el array. Por ejemplo: filtrar entradas

In [32]:
a = np.arange(0,20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
# Se verifican que numeros son mayores a 7. El resultado es un array con datos booleanos
mask = a>7
mask

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)

In [34]:
#Se evalua el array con la mascara obtenida,
a[mask] # se muestran solo los elementos que cumplieron la condicion

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Si se quieren obtener los numero que sean mayor que una cota inferior ($x > xmin$) y menor que una cota superior ($x < xmax $), se multiplica el resultado de las dos condiciones evaluadas por separado. 

In [45]:
mask1 = a>7
mask1

[False False False False False False False  True  True  True  True  True
  True  True  True  True  True  True  True  True]
[ 8  9 10 11 12 13 14 15 16 17 18 19 20]


In [46]:
a[mask1]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [48]:
mask2 = a<14
mask2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False, False, False, False,
       False, False], dtype=bool)

In [49]:
a[mask2]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [37]:
mask = (a>7)*(a<14)
mask

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False], dtype=bool)

In [38]:
a[mask]

array([ 8,  9, 10, 11, 12, 13])

In [51]:
#Tambien se pueden utilizar funciones de NumPy como el logical_and
b = np.logical_and(a>7, a<14)
b

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True, False, False, False, False, False,
       False, False], dtype=bool)

In [54]:
c = a[b]
c

array([ 8,  9, 10, 11, 12, 13])

 * * *
ALGEBRA LINEAL CON NUMPY
==========================

### Operaciones entre escalares y arrays

In [55]:
v1 = np.arange(5)
v1

array([0, 1, 2, 3, 4])

In [56]:
v1*2

array([0, 2, 4, 6, 8])

In [57]:
v1 + 2

array([2, 3, 4, 5, 6])

In [58]:
A*2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [59]:
A+2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26]])

In [60]:
v1*v1

array([ 0,  1,  4,  9, 16])

In [62]:
np.sum(v1*v1) #Producto punto o escalar entre dos vectores

30

In [45]:
A*A # Se multiplica elemento a elemento (no es una multiplicacion de matrices)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [63]:
A*v1 #Se toma cada fila de A y se multiplica por las componentes de v1

array([[ 0,  1,  4,  9, 16],
       [ 0,  6, 14, 24, 36],
       [ 0, 11, 24, 39, 56],
       [ 0, 16, 34, 54, 76],
       [ 0, 21, 44, 69, 96]])

### Algebra de matrices


Para multiplicar matrices, se puede hacer de dos formas:
   1. Se utiliza la funcion dot de numpy que puede ser aplicada a la 
   multiplicacion matriz-matriz, matriz-vector o vector-vector(producto interno)
   2. Haciendo un casting a matrix para que los operadores *, -, + queden sobrecargados

In [47]:
np.dot(A,A)

array([[ 150,  160,  170,  180,  190],
       [ 400,  435,  470,  505,  540],
       [ 650,  710,  770,  830,  890],
       [ 900,  985, 1070, 1155, 1240],
       [1150, 1260, 1370, 1480, 1590]])

In [48]:
np.dot(A,v1)

array([ 30,  80, 130, 180, 230])

In [49]:
np.dot(v1,v1)

30

In [50]:
# Haciendo el casting
M = np.matrix(A)
M

matrix([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [51]:
M*M

matrix([[ 150,  160,  170,  180,  190],
        [ 400,  435,  470,  505,  540],
        [ 650,  710,  770,  830,  890],
        [ 900,  985, 1070, 1155, 1240],
        [1150, 1260, 1370, 1480, 1590]])

In [52]:
M + M

matrix([[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28],
        [30, 32, 34, 36, 38],
        [40, 42, 44, 46, 48]])

In [53]:
M.T

matrix([[ 0,  5, 10, 15, 20],
        [ 1,  6, 11, 16, 21],
        [ 2,  7, 12, 17, 22],
        [ 3,  8, 13, 18, 23],
        [ 4,  9, 14, 19, 24]])

In [54]:
#A = np.array([[1.,2.,3.,5.],[0,-1.,2.,3.],[4.,0,0,2.],[1.,3.,0,1.]])
A = np.array([[3.,2.],[3.,4.]])
M = np.matrix(A)
M

matrix([[ 3.,  2.],
        [ 3.,  4.]])

In [55]:
M.I

matrix([[ 0.66666667, -0.33333333],
        [-0.5       ,  0.5       ]])

In [56]:
print (M*M.I)

[[ 1.  0.]
 [ 0.  1.]]


In [57]:
np.linalg.det(M)

6.0

## Procesamiento de datos

In [58]:
x = np.random.rand(20) # Crea un array con 20 numeros aleatorios entre [0,1)

In [59]:
x

array([ 0.22805884,  0.13147996,  0.59162834,  0.01609892,  0.1596889 ,
        0.58051713,  0.85565047,  0.33222481,  0.49542213,  0.22280343,
        0.84858787,  0.21242671,  0.78883623,  0.80013435,  0.88774711,
        0.51741227,  0.11330968,  0.95400589,  0.05716937,  0.19833854])

In [60]:
# suma de todos los elementos 
np.sum(x)

8.9915409391687717

In [61]:
# Promedio
np.sum(x)/len(x)

0.44957704695843859

In [62]:
# suma cumulativa del array
np.cumsum(x)

array([ 0.22805884,  0.3595388 ,  0.95116714,  0.96726607,  1.12695496,
        1.70747209,  2.56312256,  2.89534737,  3.3907695 ,  3.61357292,
        4.46216079,  4.6745875 ,  5.46342373,  6.26355808,  7.1513052 ,
        7.66871746,  7.78202714,  8.73603303,  8.7932024 ,  8.99154094])

In [63]:
# media o promedio
np.mean(x)

0.44957704695843859

In [64]:
# valor maximo y minimo del array
np.min(x),np.max(x)

(0.016098923490379446, 0.95400589155259152)

In [65]:
# el producto de todos los elementos del array
np.prod(x)

5.3215484228038969e-11

## Lectura de archivo de datos

In [17]:
# Se va a leer el archivo noble.dat
# la variable guardará los archivos de la tabla
tabla = np.loadtxt('nobles.dat')

In [18]:
#Se muestra el contenido de tabla
# que es una matriz
tabla

array([[   2.    ,    4.0026],
       [  10.    ,   20.183 ],
       [  18.    ,   39.948 ],
       [  36.    ,   83.8   ],
       [  54.    ,  131.3   ],
       [  86.    ,  222.    ]])

In [68]:
tabla[:,0] # muestra la columna 0 con todas las filas

array([  2.,  10.,  18.,  36.,  54.,  86.])

In [69]:
tabla[:,1] # muestra la columna 1 con todas las filas

array([   4.0026,   20.183 ,   39.948 ,   83.8   ,  131.3   ,  222.    ])

In [70]:
# Cada columna puede ser guardada en una variable distinta
Z = tabla[:,0] #numero atomico
P = tabla[:,1] #peso

In [81]:
# Se pueden guardar los datos en variables distinta desde la lectura del archivo
Zatomico,Patomico = np.loadtxt('nobles.dat',unpack=True)

In [82]:
Zatomico

array([  2.,  10.,  18.,  36.,  54.,  86.])

In [83]:
Patomico

array([   4.0026,   20.183 ,   39.948 ,   83.8   ,  131.3   ,  222.    ])

In [84]:
# se puede guardar un array de numpy en un archivo de datos
Zatomico = Zatomico*2.
Patomico = Patomico/2.0
DAT = np.array([Zatomico,Patomico])
np.savetxt('nobles_nuevo.dat',DAT.T,fmt='%.3f')

**DAT.T** da como resultado la transpuesta de la matriz. Esto se hace con el fin de que los datos queden guardados en 2 columnas. **DAT** es una matriz de 2 filas por 6 columnas, mientras que **DAT.T** en una matriz de 6 filas por 2 columnas. Observen:

In [85]:
DAT

array([[   4.    ,   20.    ,   36.    ,   72.    ,  108.    ,  172.    ],
       [   2.0013,   10.0915,   19.974 ,   41.9   ,   65.65  ,  111.    ]])

In [86]:
DAT.T

array([[   4.    ,    2.0013],
       [  20.    ,   10.0915],
       [  36.    ,   19.974 ],
       [  72.    ,   41.9   ],
       [ 108.    ,   65.65  ],
       [ 172.    ,  111.    ]])